### PR TITLE
#23 - fix safe_params overwriting when more than one schema definied

### LINKED ISSUE #23: cannot  define multiple schemas in one controller (safe params)
**Describe the bug**

If schema is defined more than once, it overwrite safe_params. So safe_params are only available and works for last defined schema.

**To Reproduce**

```ruby
class UsersController < ApplicationController
  schema(:show) do
    required(:id).value(:integer)
  end

  schema(:new) do
    required(:id).value(:integer)
  end

  def show
    if safe_params.success?
      render json: {id: safe_params[:id], name: "Jane"}
    else
      render json: {errors: safe_params.errors.to_h}
    end
  end

  def new
    if safe_params.success?
      render json: {id: safe_params[:id], name: "Jane"}
    else
      render json: {errors: safe_params.errors.to_h}
    end
  end
end
```

**Expected behavior**

safe params works for both defined schema, currently second works, but for `:show` safe_params are just `nil`

### PR DESCRIPTION
**Pull request by gotar**
Current PR should fix #23 Issue. I'm not sure it's the best approach.

### CODE REVIEW

File: lib/dry/rails/features/safe_params.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def schema(*actions, &block)
               schemas[name] = schema
             end
 
-            before_action(:set_safe_params, only: actions)
+            before_action(:set_safe_params)
```
Comment (solnic) [inline lib/dry/rails/features/safe_params.rb:36]: @gotar I *think* we want to move this to the `self.included` hook + tweak `set_safe_params` so that it checks if there is a schema defined for the current action.

Comment (gotar) [reply lib/dry/rails/features/safe_params.rb:36]: Hmm ok will try to tweak it later. We will see

Comment (gotar) [reply lib/dry/rails/features/safe_params.rb]: Maybe something like that, check last commit, but works without all of this tweaks too.

File: lib/dry/rails/features/safe_params.rb [hunk 2]
```diff
@@ -68,7 +70,11 @@ def schemas
 
         # @api private
         def set_safe_params
-          @safe_params = schemas[action_name.to_sym].(request.params)
+          @safe_params ||= {}
+
+          schemas.each do |action, schema|
+            @safe_params[action] = schema.(request.params)
+          end
```
Comment (solnic) [inline lib/dry/rails/features/safe_params.rb:77]: @gotar hmm why does it have to go through all defined schemas instead of just fetching a schema for the current action and setting `@safe_params`?

Comment (gotar) [reply lib/dry/rails/features/safe_params.rb:77]: When I tested, going just through defined do not work for me. Was skipping other then the last one. That was only solution that worked for me. But maybe you will find a better one? Going through all do not affect it anyhow, so I left it in that way.

Comment (solnic) [reply lib/dry/rails/features/safe_params.rb:77]: @gotar it works when you just do:

```ruby
schema = schemas[action_name.to_sym]
return unless schema
@safe_params = schema.(request.params)
```

+ removig the fetch part from `safe_params` reader.

I'll merge this in if you could tweak it like that.

**Comment by gotar** [comment]
@solnic Done

**Comment by solnic** [comment]
@gotar thanks! <3
